# Generated by Django 4.2.3 on 2023-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pdf_file', models.FileField(blank=True, help_text='Zorunlu değil', null=True, upload_to='pdfs/')),
                ('isactive', models.BooleanField(default=False, editable=False)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
    ]
